// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFJz45aFonFPyv3N8WQdPZqC9Ii1YFKFE',
    appId: '1:330400391715:android:20693825f0f20ab07b0796',
    messagingSenderId: '330400391715',
    projectId: 'registro-de-pago-3c9fe',
    storageBucket: 'registro-de-pago-3c9fe.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGCxsUsY1ZU8EEv95oq013oLi3ykJ-Aes',
    appId: '1:330400391715:web:0654972ef844fadb7b0796',
    messagingSenderId: '330400391715',
    projectId: 'registro-de-pago-3c9fe',
    authDomain: 'registro-de-pago-3c9fe.firebaseapp.com',
    storageBucket: 'registro-de-pago-3c9fe.firebasestorage.app',
    measurementId: 'G-LZ4L0VV7K5',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGCxsUsY1ZU8EEv95oq013oLi3ykJ-Aes',
    appId: '1:330400391715:web:0654972ef844fadb7b0796',
    messagingSenderId: '330400391715',
    projectId: 'registro-de-pago-3c9fe',
    authDomain: 'registro-de-pago-3c9fe.firebaseapp.com',
    storageBucket: 'registro-de-pago-3c9fe.firebasestorage.app',
    measurementId: 'G-LZ4L0VV7K5',
  );

}